[theme]

base = "dark"
primaryColor = "#fb2d2d"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1f1f1f"
textColor = "#FAFAFA"

borderColor = "#555755"
dataframeHeaderBackgroundColor = "#1F2128"

font = "sans serif"
headingFont = "sans serif"
codeFont = "monospace"

metricValueFontSize = "1.7rem" 
metricValueFontWeight = 500




