[theme]

base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#292630"
textColor = "#FAFAFA"

borderColor = "#555755"
dataframeHeaderBackgroundColor = "#1F2128"

font = "sans serif"
headingFont = "sans serif"
codeFont = "monospace"

metricValueFontSize = "1.7rem" 
metricValueFontWeight = 500




